apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/mlnawsdevops/frontend-argocd.git
    targetRevision: main
    path: .
    helm:
      releaseName: frontend
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: expense
  syncPolicy:
    automated:
      Prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true